/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.10"
    id("java")

    // Apply the application plugin to add support for building a CLI application.
    application
}

repositories {
    // Use jcenter for resolving dependencies.
    // You can declare any Maven/Ivy/file repository here.
    jcenter()
    maven { url = uri("http://repo.spongepowered.org/maven") }
    maven { url = uri("https://libraries.minecraft.net") }
    maven { url = uri("https://jitpack.io") }
    maven { url = uri("https://jcenter.bintray.com/") }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib"))

    // Use the Kotlin reflect library.
    implementation(kotlin("reflect"))

    // Use the Kotlin test library.
    testImplementation(kotlin("test-junit5"))

    // Compile Minestom into project
    implementation("com.github.Minestom:Minestom:master-SNAPSHOT")

    // KHTTP
    implementation("khttp:khttp:1.0.0")
}

application {
    // Define the main class for the application.
    mainClassName = "world.cepi.sabre.SabreKt"
}

tasks.jar {
    manifest {
        attributes (
            "Main-Class" to "world.cepi.sabre.SabreKt"
        )
    }

    from(configurations.compileClasspath.get().map {if (it.isDirectory) it else zipTree(it)}) {
        exclude("META-INF/*.RSA", "META-INF/*.SF","META-INF/*.DSA")
    }
}