/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.10"

    // Apply the application plugin to add support for building a jar
    java
}

repositories {
    // Use jcenter for resolving dependencies.
    jcenter()

    // Use mavenCentral
    maven { url = uri("https://repo1.maven.org/maven2/") }
    maven { url = uri("http://repo.spongepowered.org/maven") }
    maven { url = uri("https://libraries.minecraft.net") }
    maven { url = uri("https://jitpack.io") }
    maven { url = uri("https://jcenter.bintray.com/") }
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation(kotlin("stdlib"))

    // Use the Kotlin reflect library.
    implementation(kotlin("reflect"))

    // Use the Kotlin test library.
    testImplementation(kotlin("test-junit5"))

    // Compile Minestom into project
    implementation("com.github.Minestom:Minestom:master-SNAPSHOT")

    // Use the Netty library
    implementation("io.netty:netty-transport-native-epoll:4.1.52.Final")

    // KHTTP
    implementation("khttp:khttp:1.0.0")
}

tasks.jar {
    manifest {
        attributes (
            "Main-Class" to "world.cepi.sabre.SabreKt",
            "Multi-Release" to true
        )
    }

    from(configurations.compileClasspath.get().map { if (it.isDirectory) it else zipTree(it) }) {
        exclude("META-INF/*.RSA", "META-INF/*.SF","META-INF/*.DSA")
    }
}