/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package world.cepi.sabre

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

class AppTest {
    @Test fun testAppHasAGreeting() {
        assertTrue(true, "Testing Tests")
    }
}
